schema_version: 1

context:
  python_min: "3.11"
  version: "0.5.3"

package:
  name: aiomoto
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/aiomoto/aiomoto-${{ version }}.tar.gz
  sha256: 78a1a929a8ad7855460113eae71785cf4b15610c33b38b3432d2c1f54055eada

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.9,<0.10.0
    - pip
  run:
    - python >=${{ python_min }}
    - aiobotocore >=2.24.1,<=2.25.1
    - moto >=5.1.5,<=5.2.0
    - platformdirs >=4.0.0

tests:
  - python:
      imports:
        - aiomoto
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Moto-style AWS service mocks for aiobotocore/aioboto3
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/aiomoto/

extra:
  recipe-maintainers:
    - peterbygrave
